### ISSUE TITLE
Clarify getting started steps

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-site#1941] opened 2021-06-09 14:55 UTC
The `Get Access` section of the [cloud.gov documentation](https://github.com/cloud-gov/cg-site/blob/master/_docs/getting-started/accounts.md) states that: "If you’re in EPA, GSA, or NSF: You automatically have access and can log in using your agency credentials"

Does this mean that GSA users don't need to [create a sandbox account](https://account.fr.cloud.gov/signup)? is there a process that already exists that automates this?

If not, the documentation should be clearer that this step should be completed in the `Get Access` section listing of steps.

**Comment by loganmeetsworld** [comment] 2021-06-09 14:58
Also noting: When I went through the "create a sandbox account" process it did not create a sandbox account either. My org and space only showed up when @soutenniza kindly assisted me in the setup.

**Comment by loganmeetsworld** [comment] 2021-06-15 14:00
@mheadd I believe this has been fixed and the documentation is now correct. The issue was that the bot creating our sandboxes relied on a CSV that switched ownership recently. The sandbox app hadn't been updated, so it was getting an invalid CSV. Now that the issue is fixed the sandboxes should be created automatically for new GSA team members (h/t @bengerman13). So I believe we can close this!

**Closed as completed** 2021-06-15 14:29 UTC
