### ISSUE TITLE
Explain the new way that deployer accounts will be created in GovCloud

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#369] opened 2016-08-17 21:39 UTC
In order for our users to understand how GovCloud will work, our docs pages that talk about spaces and deployer accounts should explain that in GovCloud deployer accounts will be created automatically.

This depends on this getting implemented: https://github.com/18F/cg-product/issues/236

We'll have to look through our docs and figure out the right pages to update. This is closely related to https://github.com/18F/cg-docs/issues/368 (Clearly explain acceptable usage of deployer users) but can be done separately.

Acceptance criteria:
- [ ] Our docs make sense.

**Comment by afeld** [comment] 2016-10-27 16:48
(Long) discussion of how to tackle this starting at https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1477538944006072.

/cc https://github.com/18F/cg-site/issues/286

**Comment by mogul** [comment] 2016-10-29 22:05
#286 was deprecated in favor of https://github.com/18F/cg-product/issues/236 which is deprecated in favor of https://github.com/18F/cg-product/issues/437

**Comment by mogul** [comment] 2016-11-05 20:21
Closing as a dupe of #521 which is also now completed.

**Closed as completed by mogul** 2016-11-05 20:21 UTC
